[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
libs = ["lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 1
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
ffi = false
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[lint]
ignore = ["src/vendor/**/*.sol"]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"
